server:
  port: 8090
  servlet:
    application-display-name: electroplus-service

spring:
  application:
    name: electroplus-service

  datasource:
    url: jdbc:postgresql://ec2-23-22-191-232.compute-1.amazonaws.com:5432/d29e4g6sfefqni
    username: micyzxvkpmmtwh
    password: cefa7b7a3f2c84bcc93259dccb40717ea6da1d7a282e4d07e8d82bc573b59ab3
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 3

    initialization-mode: always
    data: classpath:data/categoria.sql,classpath:data/rol.sql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    suffix: .html
    cache: false