spring:
  datasource:
    url: jdbc:postgresql://ec2-34-225-167-77.compute-1.amazonaws.com:5432/dbbrrjvdi9ba20
    username: bcpahssazerted
    password: ${HEROKU_PSS_DB}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 3

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true